# **Importing the required Libraries**

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
iris=pd.read_csv("IRIS.csv")

In [ ]:
iris.head()

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [ ]:
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


In [ ]:
iris.describe()

sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [24]:
iris['species'].value_counts()

Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: species, dtype: int64

In [ ]:
X=iris.iloc[:,0:4].values
y=iris.iloc[:,4].values

# **Converting the categorical variable to numerical form**

In [45]:
from sklearn.preprocessing import LabelBinarizer
lb=LabelBinarizer()
y=lb.fit_transform(y)

# **Splitting the data into training and testing**

In [28]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

# **Training the model through Random Forest Classifier**

In [34]:
from sklearn.ensemble import RandomForestClassifier
rfc=RandomForestClassifier(n_estimators=100,random_state=0)
rfc.fit(X_train,y_train)

RandomForestClassifier(random_state=0)

In [37]:
y_pred=rfc.predict(X_test)

# **Evaluating the model**

In [38]:
from sklearn.metrics import confusion_matrix,accuracy_score
cm=confusion_matrix(np.argmax(y_pred,axis=1),np.argmax(y_test,axis=1))
accuracy=accuracy_score(np.argmax(y_pred,axis=1),np.argmax(y_test,axis=1))

In [43]:
print(f"Confustion Matrix: \n{cm}")

Confustion Matrix: 
[[11  0  0]
 [ 0 13  0]
 [ 0  0  6]]


In [44]:
print(f"Accuracy Scores is {accuracy*100}")

Accuracy Scores is 100.0
