In [3]:
#Create a 3×3 zero matrix
import numpy as np
matx=np.zeros((3,3),dtype=int)
print(matx)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [4]:
#Convert list [1,2,3] to NumPy array
lis=[1,2,3]
arr=np.array(lis)
print(f"array:{arr} and its type:{type(arr)}")

array:[1 2 3] and its type:<class 'numpy.ndarray'>


In [5]:
#Find mean of an array
print(arr.mean())

2.0


In [13]:
#Get second column of a matrix
matx=np.array([[3,6,9],[6,8,8],[3,9,9]])
print(f"matrix:\n{matx} \nSecond col of matrix:{matx[:,1]}")

matrix:
[[3 6 9]
 [6 8 8]
 [3 9 9]] 
Second col of matrix:[6 8 9]


In [18]:
#Reshape array of size 12 into 3×4
arr_1=np.linspace(1,12,12)
matx_1=arr_1.reshape((3,4))
print(f"Original array:\n{arr_1}\nReshaped array:\n{matx_1}")

Original array:
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.]
Reshaped array:
[[ 1.  2.  3.  4.]
 [ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]]


In [20]:
#Reshape array of size 12 into 3×4
arr_2=np.arange(1,13,1)
matx_2=arr_2.reshape((3,4))
print(f"Original array:\n{arr_2}\nReshaped array:\n{matx_2}")

Original array:
[ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshaped array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [23]:
#Find row-wise sum
print("matrix:",matx)
print("sum of rows:",np.sum(matx,axis=1))

matrix: [[3 6 9]
 [6 8 8]
 [3 9 9]]
sum of rows: [18 22 21]


In [30]:
#Generate random integers between 10 and 50
from numpy import random
def gen_ints(x,y):
    return np.random.randint(x,y)
print(gen_ints(10,50))

25


In [41]:
#Convert 2D array to 1D
r,c=list(map(int,input("Enter no of rows and columns seperated by space:").split()))
arr_2d=np.array([list(map(int,input(f"Enter {c} values of each row seperated with spaces:").split())) for _ in range(r)])
def two_one_dim(arr_2d):
    return arr_2d.flatten()
print(f"Converted 2d to 1d:{two_one_dim(arr_2d)}")

Enter no of rows and columns seperated by space: 3 2
Enter 2 values of each row seperated with spaces: 21 23
Enter 2 values of each row seperated with spaces: 12 13
Enter 2 values of each row seperated with spaces: 17 39


Converted 2d to 1d:[21 23 12 13 17 39]


In [48]:
#Add two matrices
r,c=list(map(int,input("Enter no of rows and columns seperated by spaces:").split()))
matx_a=np.array([list(map(int,input(f"Enter {c} values separated by spaces for 1st matrix:").split())) for _ in range(r)])
matx_b=np.array([list(map(int,input(f"Enter {c} values seperated by spaces for 2nd matrix:").split())) for _ in range(r)])
print(f"1st matrix:\n{matx_a}\n2nd matrix:\n{matx_b}")
def add(matx_a,matx_b):
    return np.add(matx_a,matx_b)
print("Addition of 2 matices:\n",add(matx_a,matx_b))

Enter no of rows and columns seperated by spaces: 3 2
Enter 2 values separated by spaces for 1st matrix: 15 13
Enter 2 values separated by spaces for 1st matrix: 16 17
Enter 2 values separated by spaces for 1st matrix: 19 18
Enter 2 values seperated by spaces for 2nd matrix: 23 21
Enter 2 values seperated by spaces for 2nd matrix: 32 24
Enter 2 values seperated by spaces for 2nd matrix: 26 28


1st matrix:
[[15 13]
 [16 17]
 [19 18]]
2nd matrix:
[[23 21]
 [32 24]
 [26 28]]
Addition of 2 matices:
 [[38 34]
 [48 41]
 [45 46]]


In [50]:
#Find max of each column
r,c=list(map(int,input("Enter no of rows and cols:").split()))
matx=np.array([list(map(int,input(f"Enter {c} values:").split())) for _ in range(r)])
def max_of_col(matx):
    return np.max(matx,axis=0)
print(f"Maximum value of each columns:{max_of_col(matx)}")

Enter no of rows and cols: 2 3
Enter 3 values: 12 23 24
Enter 3 values: 13 25 27


Maximum value of each columns:[13 25 27]


In [59]:
#Filter values > mean
arr=np.array(list(map(int,input("Enter values of array:").split())))
def val_greater_mean(arr):
    mean_val=np.mean(arr)
    filtered_arr=list(map(int,(filter(lambda x:x>mean_val,arr))))
    return mean_val,filtered_arr
print(val_greater_mean(arr))

Enter values of array: 1 8 9 4 3


(np.float64(5.0), [8, 9])


In [35]:
#Normalize array
import numpy as np
arr=np.array(list(map(int,input("Enter nums:").split())))
def normalize(arr):
    scale=(arr-arr.min())/(arr.max()-arr.min())
    return list(map(float,scale))
print(normalize(arr))

Enter nums: 5 3 2 8 9


[0.42857142857142855, 0.14285714285714285, 0.0, 0.8571428571428571, 1.0]


In [38]:
#Normalize array
arr=np.array(list(map(int,input("Enter values:").split())))
def standard_scale(arr):
    scale=(arr-arr.mean())/(arr.std())
    return list(map(float,scale))
print(standard_scale(arr))

Enter values: 6 9 4 2 9


[0.0, 1.0882143751650175, -0.7254762501100117, -1.4509525002200234, 1.0882143751650175]


In [14]:
#Concatenate column-wise
r,c=list(map(int,input("Enter no. of rows and columns seperated with spaces:").split()))
matx_a=np.array([list(map(int,input(f"Enter {c} values for matrix a:").split())) for _ in range(r)])
matx_b=np.array([list(map(int,input(f"Enter {c} values for matrix b:").split())) for _ in range(r)])
def concatenate(x,y):
    return np.concat((x,y),axis=0)
print(concatenate(matx_a,matx_b))

Enter no. of rows and columns seperated with spaces: 3 2
Enter 2 values for matrix a: 12 15
Enter 2 values for matrix a: 13 17
Enter 2 values for matrix a: 13 19
Enter 2 values for matrix b: 23 12
Enter 2 values for matrix b: 21 25
Enter 2 values for matrix b: 18 23


[[12 15]
 [13 17]
 [13 19]
 [23 12]
 [21 25]
 [18 23]]


In [17]:
#Concatenate column-wise
print(np.vstack((matx_a,matx_b)))

[[12 15]
 [13 17]
 [13 19]
 [23 12]
 [21 25]
 [18 23]]


In [18]:
#Concatenate row-wise
print(np.hstack((matx_a,matx_b)))

[[12 15 23 12]
 [13 17 21 25]
 [13 19 18 23]]


In [19]:
#Concatenate row-wise
print(np.concat((matx_a,matx_b),axis=1))

[[12 15 23 12]
 [13 17 21 25]
 [13 19 18 23]]


In [23]:
#Split array into 3 parts
arr_1d=matx_a.flatten()
print(arr_1d)
print(np.split(arr_1d,3))

[12 15 13 17 13 19]
[array([12, 15]), array([13, 17]), array([13, 19])]


In [26]:
#️Read array and square all elements
arr=np.array(list(map(int,input("Enter values:").split())))
def square(arr):
    return list(map(int,np.square(arr)))
print(square(arr))

Enter values: 1 5 8 9


[1, 25, 64, 81]


In [29]:
#Read matrix and find max element
n=int(input())
matx=np.array([list(map(int,input().split())) for _ in range(n)])
print(np.max(matx))

 3
 3 7 9
 4 7 9
 3 0 6


9


In [30]:
#Read matrix and print transpose
n=int(input())
matx=np.array([list(map(int,input().split())) for _ in range(n)])
print(matx.T)

 4
 3 7
 5 9
 4 0
 3 6


[[3 5 4 3]
 [7 9 0 6]]


In [31]:
#Read matrix and find row-wise sum
n=int(input())
matx=np.array([list(map(int,input().split())) for _ in range(n)])
print(np.sum(matx,axis=1))

 3
 3 6 8
 4 6 9
 1 5 9


[17 19 15]


In [33]:
#Read float array and calculate mean
def read_float_arr():
    return np.array(list(map(float,input().split())))
arr=read_float_arr()
print(arr)
print(np.mean(arr))

 3.4 6.8 9.0 5 7


[3.4 6.8 9.  5.  7. ]
6.24


In [39]:
#Normalize [5, 10, 15]
arr=np.array([5,10,15])
scale=(arr-arr.min())/(arr.max()-arr.min())
print(scale)    

[0.  0.5 1. ]


In [41]:
#Normalize a 3×3 matrix
r,c=list(map(int,input("Enter rows and columns:").split()))
def read_matx():
    matx_3=np.array([list(map(int,input(f"Enter {c} values:").split())) for _ in range(r)])
    return matx_3
matx=read_matx()
def normalize(matx):
    scaling=(matx-matx.min())/(matx.max()-matx.min())
    return scaling
print(normalize(matx))

Enter rows and columns: 2 3
Enter 3 values: 4 7 9
Enter 3 values: 12 4 8


[[0.    0.375 0.625]
 [1.    0.    0.5  ]]


In [42]:
#Normalize column-wise
r,c=list(map(int,input("Enter rows and columns:").split()))
def read_matx():
    matx_3=np.array([list(map(int,input(f"Enter {c} values:").split())) for _ in range(r)])
    return matx_3
matx=read_matx()
def normalize(matx):
    scaling=(matx-matx.min(axis=0))/(matx.max(axis=0)-matx.min(axis=0))
    return scaling
print(normalize(matx))

Enter rows and columns: 3 4
Enter 4 values: 4 12 6 18
Enter 4 values: 2 6 9 10
Enter 4 values: 12 15 3 8


[[0.2        0.66666667 0.5        1.        ]
 [0.         0.         1.         0.2       ]
 [1.         1.         0.         0.        ]]
