In [3]:
import pandas as pd
import numpy as np

Creating an array for Data Frame

In [3]:
rows=4
column=5
low=3
high=15
random_array=np.random.randint(low,high,size=(rows,column))
print(random_array)

[[10  6 10 11 14]
 [14  9 14  7  4]
 [ 6  9  9  3  5]
 [ 5 13  7 13 11]]


In [4]:
print(np.random.randint(5,10,size=(2,6)))

[[6 5 8 7 5 8]
 [6 9 6 7 9 9]]


Giving Index and column names

In [5]:
scores=np.array([[9,8,10,7,9],[8,9,9,6,8],[9,10,7,8,9]])
subjects=["Maths","Physics","Chemistry"]
column_names=["Sai Lakshmi","Rasagnya","Akhila","Kalyani","Naga Sai"]
marks_of_students=pd.DataFrame(scores,index=subjects,columns=column_names)
print(marks_of_students)

           Sai Lakshmi  Rasagnya  Akhila  Kalyani  Naga Sai
Maths                9         8      10        7         9
Physics              8         9       9        6         8
Chemistry            9        10       7        8         9


In [6]:
marks_of_students['Sai Lakshmi']

Maths        9
Physics      8
Chemistry    9
Name: Sai Lakshmi, dtype: int64

# **Creation of the Series**

In [7]:
degree_cgpa=[9.52,9.68,9.40,9.44,9.88]
my_cgpa=pd.Series(degree_cgpa,index=["1st_sem","2nd_sem","3rd_sem","4th_sem","5th_sem"])
my_cgpa

1st_sem    9.52
2nd_sem    9.68
3rd_sem    9.40
4th_sem    9.44
5th_sem    9.88
dtype: float64

In [8]:
dframe={"Subject":["Maths","Statistics","Data Science"],"Marks":[20,19,20]}
internal=pd.DataFrame(dframe)
internal

Subject  Marks
0         Maths     20
1    Statistics     19
2  Data Science     20

In [4]:
df=pd.read_csv('/content/sample_data/california_housing_train.csv')

In [5]:
df.head(10)

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -114.31     34.19                15.0       5612.0          1283.0   
1    -114.47     34.40                19.0       7650.0          1901.0   
2    -114.56     33.69                17.0        720.0           174.0   
3    -114.57     33.64                14.0       1501.0           337.0   
4    -114.57     33.57                20.0       1454.0           326.0   
5    -114.58     33.63                29.0       1387.0           236.0   
6    -114.58     33.61                25.0       2907.0           680.0   
7    -114.59     34.83                41.0        812.0           168.0   
8    -114.59     33.61                34.0       4789.0          1175.0   
9    -114.60     34.83                46.0       1497.0           309.0   

   population  households  median_income  median_house_value  
0      1015.0       472.0         1.4936             66900.0  
1      1129.0       463.0         1.8200             80100.0  
2       333.0       117.0         1.6509             85700.0  
3       515.0       226.0         3.1917             73400.0  
4       624.0       262.0         1.9250             65500.0  
5       671.0       239.0         3.3438             74000.0  
6      1841.0       633.0         2.6768             82400.0  
7       375.0       158.0         1.7083             48500.0  
8      3134.0      1056.0         2.1782             58400.0  
9       787.0       271.0         2.1908             48100.0

In [6]:
df.tail(4)

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
16996    -124.27     40.69                36.0       2349.0           528.0   
16997    -124.30     41.84                17.0       2677.0           531.0   
16998    -124.30     41.80                19.0       2672.0           552.0   
16999    -124.35     40.54                52.0       1820.0           300.0   

       population  households  median_income  median_house_value  
16996      1194.0       465.0         2.5179             79000.0  
16997      1244.0       456.0         3.0313            103600.0  
16998      1298.0       478.0         1.9797             85800.0  
16999       806.0       270.0         3.0147             94600.0

In [7]:
df.shape

(17000, 9)

In [8]:
df.columns

Index(['longitude', 'latitude', 'housing_median_age', 'total_rooms',
       'total_bedrooms', 'population', 'households', 'median_income',
       'median_house_value'],
      dtype='object')

In [9]:
df.index

RangeIndex(start=0, stop=17000, step=1)

In [12]:
df=df.rename(columns={'longitude':'longtd','latitude':'latitd','total_bedrooms':'no_of_bedrooms'})
df.columns

Index(['longtd', 'latitd', 'housing_median_age', 'total_rooms',
       'no_of_bedrooms', 'population', 'households', 'median_income',
       'median_house_value'],
      dtype='object')

# Statistical Description

In [13]:
df.describe()

longtd        latitd  housing_median_age   total_rooms  \
count  17000.000000  17000.000000        17000.000000  17000.000000   
mean    -119.562108     35.625225           28.589353   2643.664412   
std        2.005166      2.137340           12.586937   2179.947071   
min     -124.350000     32.540000            1.000000      2.000000   
25%     -121.790000     33.930000           18.000000   1462.000000   
50%     -118.490000     34.250000           29.000000   2127.000000   
75%     -118.000000     37.720000           37.000000   3151.250000   
max     -114.310000     41.950000           52.000000  37937.000000   

       no_of_bedrooms    population    households  median_income  \
count    17000.000000  17000.000000  17000.000000   17000.000000   
mean       539.410824   1429.573941    501.221941       3.883578   
std        421.499452   1147.852959    384.520841       1.908157   
min          1.000000      3.000000      1.000000       0.499900   
25%        297.000000    790.000000    282.000000       2.566375   
50%        434.000000   1167.000000    409.000000       3.544600   
75%        648.250000   1721.000000    605.250000       4.767000   
max       6445.000000  35682.000000   6082.000000      15.000100   

       median_house_value  
count        17000.000000  
mean        207300.912353  
std         115983.764387  
min          14999.000000  
25%         119400.000000  
50%         180400.000000  
75%         265000.000000  
max         500001.000000

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17000 entries, 0 to 16999
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longtd              17000 non-null  float64
 1   latitd              17000 non-null  float64
 2   housing_median_age  17000 non-null  float64
 3   total_rooms         17000 non-null  float64
 4   no_of_bedrooms      17000 non-null  float64
 5   population          17000 non-null  float64
 6   households          17000 non-null  float64
 7   median_income       17000 non-null  float64
 8   median_house_value  17000 non-null  float64
dtypes: float64(9)
memory usage: 1.2 MB


Transpose the above

In [15]:
df.describe().T

count           mean            std         min  \
longtd              17000.0    -119.562108       2.005166   -124.3500   
latitd              17000.0      35.625225       2.137340     32.5400   
housing_median_age  17000.0      28.589353      12.586937      1.0000   
total_rooms         17000.0    2643.664412    2179.947071      2.0000   
no_of_bedrooms      17000.0     539.410824     421.499452      1.0000   
population          17000.0    1429.573941    1147.852959      3.0000   
households          17000.0     501.221941     384.520841      1.0000   
median_income       17000.0       3.883578       1.908157      0.4999   
median_house_value  17000.0  207300.912353  115983.764387  14999.0000   

                              25%          50%         75%          max  
longtd                -121.790000    -118.4900    -118.000    -114.3100  
latitd                  33.930000      34.2500      37.720      41.9500  
housing_median_age      18.000000      29.0000      37.000      52.0000  
total_rooms           1462.000000    2127.0000    3151.250   37937.0000  
no_of_bedrooms         297.000000     434.0000     648.250    6445.0000  
population             790.000000    1167.0000    1721.000   35682.0000  
households             282.000000     409.0000     605.250    6082.0000  
median_income            2.566375       3.5446       4.767      15.0001  
median_house_value  119400.000000  180400.0000  265000.000  500001.0000

Extract single column

In [16]:
df['median_house_value'].head(5)

0    66900.0
1    80100.0
2    85700.0
3    73400.0
4    65500.0
Name: median_house_value, dtype: float64

In [17]:
df[['median_house_value']].head(5)

median_house_value
0             66900.0
1             80100.0
2             85700.0
3             73400.0
4             65500.0

from matplotlib import pyplot as plt
_df_0['median_house_value'].plot(kind='hist', bins=20, title='median_house_value')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_1['median_house_value'].plot(kind='line', figsize=(8, 4), title='median_house_value')
plt.gca().spines[['top', 'right']].set_visible(False)

**To extract multiple columns**



In [18]:
df[['median_house_value','median_income']].head(3)

median_house_value  median_income
0             66900.0         1.4936
1             80100.0         1.8200
2             85700.0         1.6509

# **Adding New Column**

In [20]:
df['rooms_bedrooms']=df['total_rooms']+df['no_of_bedrooms']
df['rooms_bedrooms']

0        6895.0
1        9551.0
2         894.0
3        1838.0
4        1780.0
          ...  
16995    2611.0
16996    2877.0
16997    3208.0
16998    3224.0
16999    2120.0
Name: rooms_bedrooms, Length: 17000, dtype: float64

In [21]:
df['rooms_bedrooms'].tail(2)

16998    3224.0
16999    2120.0
Name: rooms_bedrooms, dtype: float64

# **Drop the column**

In [22]:
df.drop("rooms_bedrooms",axis=1,inplace=True)

In [23]:
df.head(1)

longtd  latitd  housing_median_age  total_rooms  no_of_bedrooms  \
0 -114.31   34.19                15.0       5612.0          1283.0   

   population  households  median_income  median_house_value  
0      1015.0       472.0         1.4936             66900.0

**Drop Multiple columns**

In [25]:
df.drop(columns=['longtd','latitd']).head(2)

housing_median_age  total_rooms  no_of_bedrooms  population  households  \
0                15.0       5612.0          1283.0      1015.0       472.0   
1                19.0       7650.0          1901.0      1129.0       463.0   

   median_income  median_house_value  
0         1.4936             66900.0  
1         1.8200             80100.0

**set any columns as index**

In [26]:
df.set_index('housing_median_age').head()

longtd  latitd  total_rooms  no_of_bedrooms  population  \
housing_median_age                                                            
15.0               -114.31   34.19       5612.0          1283.0      1015.0   
19.0               -114.47   34.40       7650.0          1901.0      1129.0   
17.0               -114.56   33.69        720.0           174.0       333.0   
14.0               -114.57   33.64       1501.0           337.0       515.0   
20.0               -114.57   33.57       1454.0           326.0       624.0   

                    households  median_income  median_house_value  
housing_median_age                                                 
15.0                     472.0         1.4936             66900.0  
19.0                     463.0         1.8200             80100.0  
17.0                     117.0         1.6509             85700.0  
14.0                     226.0         3.1917             73400.0  
20.0                     262.0         1.9250             65500.0

**reset index**

In [27]:
df.reset_index().head(3)

index  longtd  latitd  housing_median_age  total_rooms  no_of_bedrooms  \
0      0 -114.31   34.19                15.0       5612.0          1283.0   
1      1 -114.47   34.40                19.0       7650.0          1901.0   
2      2 -114.56   33.69                17.0        720.0           174.0   

   population  households  median_income  median_house_value  
0      1015.0       472.0         1.4936             66900.0  
1      1129.0       463.0         1.8200             80100.0  
2       333.0       117.0         1.6509             85700.0